[package]
name = "wally"
version = "0.1.0"
description = "Wally Wallet and Proxy"
authors = ["you"]
edition = "2021"

[lib]
name = "wally_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.5", features = [] }

[dependencies]
tauri = { version = "2.2.3", features = ["devtools", "tray-icon", "image-png"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-http = "2"
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
tauri-plugin-deep-link = "2"
tauri-plugin-notification = "2"
tauri-plugin-barcode-scanner = "2"
log = "0.4.22"
tokio = { version = "1.0", features = ["full"] }
tokio-tungstenite = "0.21"
futures-util = "0.3"
reqwest = { version = "0.12", features = ["json", "rustls-tls-webpki-roots", "socks"], default-features = false }
axum = "0.7"
tower = "0.4"
tower-http = { version = "0.5", features = ["cors"] }
nostr = { version = "0.43", default-features = false, features = ["std"] }
nostr-sdk = { version = "0.43", default-features = false, features = ["nip04", "nip47"] }
nostr-relay-pool = { version = "0.43", default-features = false }
lightning-invoice = "0.32"
uuid = { version = "1.0", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
anyhow = "1.0"
thiserror = "1.0"
urlencoding = "2.1"
bip39 = { version = "2", default-features = false, features = ["std", "rand"] }
directories = "5"
sha2 = "0.10"
rusqlite = { version = "0.31", features = ["bundled"] }
cdk = { git = "https://github.com/gudnuf/cdk", branch = "nut18-no-transport", default-features = false, features = ["wallet", "mint"] }
cdk-sqlite = { git = "https://github.com/gudnuf/cdk", branch = "nut18-no-transport", default-features = false, features = ["wallet"] }
bitcoin_hashes = { version = "0.13", features = ["std"], default-features = false }

[target.'cfg(any(target_os = "android", target_os = "ios"))'.dependencies]
tauri-plugin-barcode-scanner = "2"
